name: Build and push

on:
  push:
    branches:
      - main
  schedule:
    # Every monday at 12am utc
    - cron:  "0 12 * * 1"
  workflow_dispatch:
  pull_request:

env:
  TARGET_PLATFORMS: linux/amd64, linux/arm/v8, linux/arm/v7, linux/arm/v6

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.TARGET_PLATFORMS }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: docker_metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository_owner }}/nginx-with-substitutions-filter
            ghcr.io/${{ github.repository_owner }}/nginx-with-substitutions-filter
          tags: |
            type=sha
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=schedule
          flavor: |
            latest=true

      - name: Build test image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          tags: nginx-with-substitutions-filter:github-actions-test
          cache-from: type=gha
          cache-to: |
            type=local,dest=${{ runner.temp }}/buildx-local-cache
            type=gha,mode=max

      - name: Test
        run: |
          ./test.sh nginx-with-substitutions-filter:github-actions-test

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          platforms: ${{ env.TARGET_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
          cache-from: |
            type=local,src=${{ runner.temp }}/buildx-local-cache
            type=gha
          cache-to: type=gha,mode=max
