name: Build

on:
  push:
    branches:
      - main
  schedule:
    # Every monday at 12am utc
    - cron:  "0 12 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: docker_metadata
        uses: docker/metadata-action@v3
        with:
          images: >-
            ${{ github.actor }}/nginx-with-substitutions-filter,
            ghcr.io/${{ github.actor }}/nginx-with-substitutions-filter
          tags: |
            type=sha
            type=ref,event=tag
          flavor: |
            latest=true

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.docker_metadata.outputs.tags }}